#spring.application.name=apigateway

server:
  port: 8080
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-keycloak-realm
  cloud:
    gateway:
      routes:
        - id: keycloakservice
          uri: lb://keycloakservice
          predicates:
            - Path=/realms/spring-keycloak-realm/protocol/openid-connect/token
        - id: productoservice
          uri: lb://ProductoService
          predicates:
            - Path=/producto/**
        - id: ordenservice
          uri: lb://OrdenService
          predicates:
            - Path=/orden/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8787/eureka
