#spring.application.name=apigateway

server:
  port: 8383
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: productoservice
          uri: lb://ProductoService
          predicates:
            - Path=/producto/**
          filters:
            - AddRequestHeader=Authorization, "#{T(org.springframework.security.core.context.SecurityContextHolder).getContext().getAuthentication().getCredentials()}"
        - id: ordenservice
          uri: lb://OrdenService
          predicates:
            - Path=/orden/**
          filters:
            - AddRequestHeader=Authorization, "#{T(org.springframework.security.core.context.SecurityContextHolder).getContext().getAuthentication().getCredentials()}"
          messages:
            encoding: UTF-8
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-container:8080/realms/spring-keycloak-realm
eureka:
  client:
    serviceUrl:
      defaultZone: http://discoveryserver:8787/eureka
      register-with-eureka: true
      fetch-registry: true