#spring.application.name=apigateway

server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: productoservice
          uri: lb://ProductoService
          predicates:
            - Path=/producto/**
        - id: ordenservice
          uri: lb://OrdenService
          predicates:
            - Path=/orden/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-keyclock-realm
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8787/eureka
